repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-annotations-complexity,
            flake8_builtins,
            flake8-eradicate,
            flake8_pep3101,
            flake8-print,
        ]
