version: "3.8"

services:
  nftgram-bot:
    build: .
    container_name: nftgram
    depends_on:
      - nftgram-database
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  nftgram-database:
    image: redis
    container_name: ${DATABASE_HOST}
    environment:
     - REDIS_REPLICATION_MODE=master
    command: redis-server --port ${DATABASE_PORT} --requirepass ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
     - ./data:/data
